"""replace komitent iban/swift with dinarski_racuni and devizni_racuni JSON

Revision ID: 101eb1ecfbe2
Revises: de160a96d4dd
Create Date: 2025-10-29 16:18:04.277329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '101eb1ecfbe2'
down_revision = 'de160a96d4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new columns
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dinarski_racuni', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('devizni_racuni', sa.JSON(), nullable=True))

    # Step 2: Data migration - migrate existing iban/swift to devizni_racuni
    # Using raw SQL to update rows where iban and swift exist
    connection = op.get_bind()
    komitenti = connection.execute(sa.text(
        "SELECT id, iban, swift FROM komitenti WHERE iban IS NOT NULL AND swift IS NOT NULL"
    ))

    for komitent in komitenti:
        devizni_racuni_json = sa.text(
            "UPDATE komitenti SET devizni_racuni = :devizni_racuni WHERE id = :id"
        )
        connection.execute(
            devizni_racuni_json,
            {
                'id': komitent.id,
                'devizni_racuni': f'[{{"banka": "Unknown", "iban": "{komitent.iban}", "swift": "{komitent.swift}", "valuta": "EUR"}}]'
            }
        )

    # Step 3: Drop old columns
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.drop_column('iban')
        batch_op.drop_column('swift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('swift', mysql.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('iban', mysql.VARCHAR(length=34), nullable=True))
        batch_op.drop_column('devizni_racuni')
        batch_op.drop_column('dinarski_racuni')

    # ### end Alembic commands ###
