"""add brojac_avansne column to pausaln_firma

Revision ID: 3ad525cba764
Revises: 74e23dace0c1
Create Date: 2025-11-06 19:06:18.117217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad525cba764'
down_revision = '74e23dace0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pausaln_firma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brojac_avansne', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pausaln_firma', schema=None) as batch_op:
        batch_op.drop_column('brojac_avansne')

    # ### end Alembic commands ###
