"""add email fields to faktura

Revision ID: 74e23dace0c1
Revises: f047a4c408fa
Create Date: 2025-11-04 20:14:58.099040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e23dace0c1'
down_revision = 'f047a4c408fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_status', sa.Enum('not_sent', 'sending', 'sent', 'failed', name='email_status_fakture'), nullable=False))
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_recipient', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        batch_op.drop_column('email_error_message')
        batch_op.drop_column('email_recipient')
        batch_op.drop_column('email_sent_at')
        batch_op.drop_column('email_status')

    # ### end Alembic commands ###
