"""add iban and swift to komitenti

Revision ID: 8e7d081a7c9a
Revises: df10529de9c5
Create Date: 2025-10-27 21:13:27.360871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7d081a7c9a'
down_revision = 'df10529de9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(length=34), nullable=True))
        batch_op.add_column(sa.Column('swift', sa.String(length=11), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.drop_column('swift')
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
