"""add profaktura conversion fields

Revision ID: a1b2c3d4e5f6
Revises: 3ad525cba764
Create Date: 2025-11-06 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '3ad525cba764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        # Add new foreign key columns for profaktura conversion linking
        batch_op.add_column(sa.Column('konvertovana_iz_profakture_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('konvertovana_u_fakturu_id', sa.Integer(), nullable=True))

        # Create foreign key constraints
        batch_op.create_foreign_key(
            'fk_konvertovana_iz_profakture',
            'fakture',
            ['konvertovana_iz_profakture_id'],
            ['id'],
            ondelete='SET NULL'
        )
        batch_op.create_foreign_key(
            'fk_konvertovana_u_fakturu',
            'fakture',
            ['konvertovana_u_fakturu_id'],
            ['id'],
            ondelete='SET NULL'
        )

        # Create index for performance
        batch_op.create_index('idx_profaktura_link', ['konvertovana_iz_profakture_id'])

    # Update status ENUM to include 'konvertovana'
    # For SQLite: recreate the column with new ENUM values
    # For MySQL/PostgreSQL: alter the ENUM type
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        # Drop and recreate the status column with updated ENUM
        batch_op.alter_column('status',
            existing_type=sa.Enum('draft', 'izdata', 'stornirana', name='status_fakture'),
            type_=sa.Enum('draft', 'izdata', 'stornirana', 'konvertovana', name='status_fakture'),
            nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        # Revert status ENUM to original values
        batch_op.alter_column('status',
            existing_type=sa.Enum('draft', 'izdata', 'stornirana', 'konvertovana', name='status_fakture'),
            type_=sa.Enum('draft', 'izdata', 'stornirana', name='status_fakture'),
            nullable=False
        )

    with op.batch_alter_table('fakture', schema=None) as batch_op:
        # Drop index
        batch_op.drop_index('idx_profaktura_link')

        # Drop foreign key constraints
        batch_op.drop_constraint('fk_konvertovana_iz_profakture', type_='foreignkey')
        batch_op.drop_constraint('fk_konvertovana_u_fakturu', type_='foreignkey')

        # Drop columns
        batch_op.drop_column('konvertovana_u_fakturu_id')
        batch_op.drop_column('konvertovana_iz_profakture_id')

    # ### end Alembic commands ###
