"""Create initial database schema with all tables

Revision ID: b10abe0f4f9f
Revises: 
Create Date: 2025-10-12 12:06:14.090068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b10abe0f4f9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pausaln_firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pib', sa.String(length=9), nullable=False),
    sa.Column('maticni_broj', sa.String(length=8), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('adresa', sa.String(length=255), nullable=False),
    sa.Column('broj', sa.String(length=20), nullable=False),
    sa.Column('postanski_broj', sa.String(length=10), nullable=False),
    sa.Column('mesto', sa.String(length=100), nullable=False),
    sa.Column('drzava', sa.String(length=50), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('dinarski_racuni', mysql.JSON(), nullable=False),
    sa.Column('devizni_racuni', mysql.JSON(), nullable=True),
    sa.Column('prefiks_fakture', sa.String(length=10), nullable=True),
    sa.Column('sufiks_fakture', sa.String(length=10), nullable=True),
    sa.Column('brojac_fakture', sa.Integer(), nullable=False),
    sa.Column('brojac_profakture', sa.Integer(), nullable=False),
    sa.Column('pdv_kategorija', sa.String(length=10), nullable=False),
    sa.Column('sifra_osnova', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pausaln_firma', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pausaln_firma_pib'), ['pib'], unique=True)

    op.create_table('artikli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('podrazumevana_cena', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('jedinica_mere', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['pausaln_firma.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artikli', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artikli_firma_id'), ['firma_id'], unique=False)

    op.create_table('komitenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('pib', sa.String(length=9), nullable=False),
    sa.Column('maticni_broj', sa.String(length=8), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('adresa', sa.String(length=255), nullable=False),
    sa.Column('broj', sa.String(length=20), nullable=False),
    sa.Column('postanski_broj', sa.String(length=10), nullable=False),
    sa.Column('mesto', sa.String(length=100), nullable=False),
    sa.Column('drzava', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['pausaln_firma.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.create_index('idx_firma_pib', ['firma_id', 'pib'], unique=False)
        batch_op.create_index(batch_op.f('ix_komitenti_firma_id'), ['firma_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_komitenti_pib'), ['pib'], unique=False)

    op.create_table('memorandumi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['pausaln_firma.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memorandumi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memorandumi_firma_id'), ['firma_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pausalac', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['pausaln_firma.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_firma_id'), ['firma_id'], unique=False)

    op.create_table('fakture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('komitent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broj_fakture', sa.String(length=50), nullable=False),
    sa.Column('tip_fakture', sa.Enum('standardna', 'profaktura', 'avansna', name='tip_fakture'), nullable=False),
    sa.Column('valuta_fakture', sa.Enum('RSD', 'EUR', 'USD', 'GBP', 'CHF', name='valuta_fakture'), nullable=False),
    sa.Column('jezik', sa.Enum('sr', 'en', name='jezik_fakture'), nullable=False),
    sa.Column('datum_prometa', sa.Date(), nullable=False),
    sa.Column('valuta_placanja', sa.Integer(), nullable=False),
    sa.Column('datum_dospeca', sa.Date(), nullable=False),
    sa.Column('broj_ugovora', sa.String(length=100), nullable=True),
    sa.Column('broj_odluke', sa.String(length=100), nullable=True),
    sa.Column('broj_narudzbenice', sa.String(length=100), nullable=True),
    sa.Column('poziv_na_broj', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=10), nullable=True),
    sa.Column('ukupan_iznos_rsd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ukupan_iznos_originalna_valuta', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('srednji_kurs', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.Enum('draft', 'izdata', 'stornirana', name='status_fakture'), nullable=False),
    sa.Column('avansna_faktura_id', sa.Integer(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avansna_faktura_id'], ['fakture.id'], ),
    sa.ForeignKeyConstraint(['firma_id'], ['pausaln_firma.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['komitent_id'], ['komitenti.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firma_id', 'broj_fakture', name='uq_firma_broj')
    )
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        batch_op.create_index('idx_firma_status', ['firma_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fakture_broj_fakture'), ['broj_fakture'], unique=False)
        batch_op.create_index(batch_op.f('ix_fakture_firma_id'), ['firma_id'], unique=False)

    op.create_table('faktura_stavke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.Column('artikal_id', sa.Integer(), nullable=True),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('kolicina', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('jedinica_mere', sa.String(length=20), nullable=False),
    sa.Column('cena', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ukupno', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('redni_broj', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artikal_id'], ['artikli.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faktura_id'], ['fakture.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faktura_stavke', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faktura_stavke_faktura_id'), ['faktura_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faktura_stavke', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faktura_stavke_faktura_id'))

    op.drop_table('faktura_stavke')
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fakture_firma_id'))
        batch_op.drop_index(batch_op.f('ix_fakture_broj_fakture'))
        batch_op.drop_index('idx_firma_status')

    op.drop_table('fakture')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_firma_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('memorandumi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memorandumi_firma_id'))

    op.drop_table('memorandumi')
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_komitenti_pib'))
        batch_op.drop_index(batch_op.f('ix_komitenti_firma_id'))
        batch_op.drop_index('idx_firma_pib')

    op.drop_table('komitenti')
    with op.batch_alter_table('artikli', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artikli_firma_id'))

    op.drop_table('artikli')
    with op.batch_alter_table('pausaln_firma', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pausaln_firma_pib'))

    op.drop_table('pausaln_firma')
    # ### end Alembic commands ###
