"""add memorandum fields for story 4.6

Revision ID: d409b6335df1
Revises: 8055af3bbcdc
Create Date: 2025-11-09 17:28:32.676013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd409b6335df1'
down_revision = '8055af3bbcdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorandumi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('naslov', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('sadrzaj', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('datum', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('komitent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('faktura_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_memorandumi_faktura_id'), ['faktura_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memorandumi_komitent_id'), ['komitent_id'], unique=False)
        batch_op.create_foreign_key(None, 'komitenti', ['komitent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'fakture', ['faktura_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memorandumi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_memorandumi_komitent_id'))
        batch_op.drop_index(batch_op.f('ix_memorandumi_faktura_id'))
        batch_op.drop_column('faktura_id')
        batch_op.drop_column('komitent_id')
        batch_op.drop_column('datum')
        batch_op.drop_column('sadrzaj')
        batch_op.drop_column('naslov')

    # ### end Alembic commands ###
