"""Add kontakt_osoba and napomene optional fields to Komitent model

Revision ID: df10529de9c5
Revises: b10abe0f4f9f
Create Date: 2025-10-25 20:18:40.307674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df10529de9c5'
down_revision = 'b10abe0f4f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kontakt_osoba', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('napomene', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('komitenti', schema=None) as batch_op:
        batch_op.drop_column('napomene')
        batch_op.drop_column('kontakt_osoba')

    # ### end Alembic commands ###
