"""add status_pdf field to faktura model

Revision ID: f047a4c408fa
Revises: 101eb1ecfbe2
Create Date: 2025-11-01 12:47:07.830980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f047a4c408fa'
down_revision = '101eb1ecfbe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_pdf', sa.Enum('pending', 'generating', 'generated', 'failed', name='status_pdf_fakture'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fakture', schema=None) as batch_op:
        batch_op.drop_column('status_pdf')

    # ### end Alembic commands ###
